serial_no: 17502551
cam_name: "camera1"
yaml_url: "package://ximea_camera/calib/camera1.yaml"
exposure_time: 10000
rect_left: 160
rect_top: 128
rect_height: 256
rect_width: 320
image_data_format: "XI_MONO8"
